language: dart

dart:
  - dev

jobs:
  include:
  - script: pub run --enable-experiment=non-nullable test
  - dart_task: dartfmt
  - dart_task:
      dartanalyzer: --enable-experiment=non-nullable --fatal-infos --fatal-warnings .
  - script: pub run --enable-experiment=non-nullable test -p chrome

# Only building master means that we don't run two builds for each pull request.
# Temporarily adding `null_safety`
branches:
  only: [master, null_safety]

cache:
 directories:
   - $HOME/.pub-cache
